# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-23 02:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('StudentID', models.AutoField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('major', models.CharField(max_length=50)),
                ('graduationDate', models.DateField()),
            ],
            options={
                'db_table': 'student',
                'managed': False,
            },
        ),
    ]
