# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-28 17:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('courseid', models.AutoField(primary_key=True, serialize=False)),
                ('coursecode', models.CharField(max_length=10)),
                ('coursename', models.CharField(max_length=50)),
                ('school', models.CharField(max_length=50)),
                ('genedflag', models.BooleanField(default=False)),
                ('coursetime', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('instructorid', models.AutoField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('rating', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('progressid', models.AutoField(primary_key=True, serialize=False)),
                ('completionflag', models.BooleanField(default=False)),
                ('genedlist', models.CharField(max_length=200)),
                ('courseid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic.Course')),
                ('studentid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic.Student')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='instructorid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic.Instructor'),
        ),
    ]
