# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-26 17:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0003_flightplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.CharField(default=b'user@louisville.edu', max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='password',
            field=models.CharField(default=b'password', max_length=20),
        ),
    ]
