# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-07 20:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('basic', '0004_auto_20161026_1715'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('major', models.CharField(max_length=10)),
                ('graddate', models.DateField()),
                ('progress', models.TextField()),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='progress',
            name='courseid',
        ),
        migrations.RemoveField(
            model_name='progress',
            name='studentid',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='coursename',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='instructor',
            old_name='firstname',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='instructor',
            old_name='lastname',
            new_name='last_name',
        ),
        migrations.RemoveField(
            model_name='course',
            name='school',
        ),
        migrations.AddField(
            model_name='course',
            name='days',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='subject',
            field=models.CharField(default='CECS', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='units',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flightplan',
            name='graddate',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flightplan',
            name='major',
            field=models.CharField(default='CECS', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='instructor',
            name='email',
            field=models.EmailField(default='test@louisville.edu', max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='coursetime',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='Progress',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
