# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-19 22:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0005_auto_20161107_2039'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='req',
            field=models.CharField(default='none', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flightplan',
            name='majorname',
            field=models.CharField(default='none', max_length=50),
            preserve_default=False,
        ),
    ]
