# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-21 07:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('basic', '0007_studentinfo_schedule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentinfo',
            name='userid',
        ),
        migrations.AddField(
            model_name='studentinfo',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
