# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-01 01:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0009_auto_20161121_0704'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='instructorid',
        ),
        migrations.AddField(
            model_name='course',
            name='instructor',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Instructor',
        ),
    ]
