# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-07 09:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0011_studentinfo_credithour'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentinfo',
            name='desiredhours',
            field=models.CharField(default="Don't Care", max_length=20),
            preserve_default=False,
        ),
    ]
